management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  health:
    probes:
      enabled: true
  server.port: ${META_PORT:8080}

spring.lifecycle.timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:1s}

server:
  shutdown: ${SHUTDOWN:immediate}
